package models

import (
	"log"
	"time"
)

// SeedDB populates the database with mock employees and 3 months of completed
// payroll history. This gives the analytics service enough data to calculate
// a meaningful average burn rate. Uses FirstOrCreate so it is safe to run
// multiple times without creating duplicate records.
func SeedDB() {
	// 1. Create mock employees covering a range of salary bands.
	employees := []Employee{
		{Name: "John Doe", Email: "john@example.com", AccountNumber: "0123456789", BankCode: "058", Salary: 250000, IsActive: true},
		{Name: "Jane Smith", Email: "jane@example.com", AccountNumber: "9876543210", BankCode: "011", Salary: 350000, IsActive: true},
		{Name: "Bob Wilson", Email: "bob@example.com", AccountNumber: "1122334455", BankCode: "044", Salary: 150000, IsActive: true},
	}

	for _, emp := range employees {
		if err := DB.FirstOrCreate(&emp, Employee{Email: emp.Email}).Error; err != nil {
			log.Printf("Could not seed employee %s: %v", emp.Email, err)
		}
	}

	// 2. Create 3 months of completed payroll history used by the analytics service.
	periods := []string{"February 2026", "March 2026", "April 2026"}
	for i, period := range periods {
		payroll := Payroll{
			Period:      period,
			TotalAmount: 750000, // Sum of salaries
			Status:      PayrollCompleted,
			CreatedAt:   time.Now().AddDate(0, -3+i, 0),
		}
		
		if err := DB.FirstOrCreate(&payroll, Payroll{Period: period}).Error; err != nil {
			log.Printf("Could not seed payroll %s: %v", period, err)
			continue
		}

		// Add items for each payroll
		// Re-fetch the employee by email to get the DB-assigned ID generated by BeforeCreate.
		for _, emp := range employees {
			var dbEmp Employee
			DB.Where("email = ?", emp.Email).First(&dbEmp)
			
			item := PayrollItem{
				PayrollID:    payroll.ID,
				EmployeeID:   dbEmp.ID,
				EmployeeName: dbEmp.Name,
				Amount:       dbEmp.Salary,
				Status:       PayrollCompleted,
			}
			DB.FirstOrCreate(&item, PayrollItem{PayrollID: payroll.ID, EmployeeID: dbEmp.ID})
		}
	}

	log.Println("Database seeded with mock employees and 3 months of history.")
}
